// Generated from AMD FidelityFX FSR1. See FSR-LICENSE.txt and ffx_fsr1.h.
#include <metal_stdlib>
using namespace metal;
float ARcpF1(float x) { return fabs(x) < 1e-8f ? 0.0f : 1.0f/x; }
float APrxLoRcpF1(float x) { return ARcpF1(x); }
float APrxMedRcpF1(float x) { return ARcpF1(x); }
float APrxLoRsqF1(float x) { return rsqrt(max(x, 1e-8f)); }
float ASatF1(float x) { return clamp(x,0.0f,1.0f); }
float AMin3F1(float a,float b,float c) { return min(a,min(b,c)); }
float AMax3F1(float a,float b,float c) { return max(a,max(b,c)); }
float3 AMin3F3(float3 a,float3 b,float3 c) { return min(a,min(b,c)); }
float3 AMax3F3(float3 a,float3 b,float3 c) { return max(a,max(b,c)); }
float2 AF2_AU2(uint2 x) { return as_type<float2>(x); }
float AF1_AU1(uint x) { return as_type<float>(x); }
#define FSR_RCAS_LIMIT (0.25f-(1.0f/16.0f))
struct FSR {
 texture2d<float,access::read> src;
 float4 load(int2 p) { return src.read(uint2(clamp(p,int2(0),int2(src.get_width()-1,src.get_height()-1)))); }
 float4 gather(float2 p,uint channel) {
  int2 base=int2(floor(p*float2(src.get_width(),src.get_height())-0.5f));
  return float4(load(base+int2(0,1))[channel],load(base+int2(1,1))[channel],load(base+int2(1,0))[channel],load(base)[channel]);
 }
 float4 FsrEasuRF(float2 p) { return gather(p,0); }
 float4 FsrEasuGF(float2 p) { return gather(p,1); }
 float4 FsrEasuBF(float2 p) { return gather(p,2); }
 float4 FsrRcasLoadF(int2 p) { return load(p); }
 void FsrRcasInputF(thread float& r,thread float& g,thread float& b) {}
 void FsrEasuTapF(
 thread float3& aC, // Accumulated color, with negative lobe.
 thread float& aW, // Accumulated weight.
 float2 off, // Pixel offset from resolve position to tap.
 float2 dir, // Gradient direction.
 float2 len, // Length.
 float lob, // Negative lobe strength.
 float clp, // Clipping point.
 float3 c){ // Tap color.
  // Rotate offset by direction.
  float2 v;
  v.x=(off.x*( dir.x))+(off.y*dir.y);
  v.y=(off.x*(-dir.y))+(off.y*dir.x);
  // Anisotropy.
  v*=len;
  // Compute distance^2.
  float d2=v.x*v.x+v.y*v.y;
  // Limit to the window as at corner, 2 taps can easily be outside.
  d2=min(d2,clp);
  // Approximation of lancos2 without sin() or rcp(), or sqrt() to get x.
  //  (25/16 * (2/5 * x^2 - 1)^2 - (25/16 - 1)) * (1/4 * x^2 - 1)^2
  //  |_______________________________________|   |_______________|
  //                   base                             window
  // The general form of the 'base' is,
  //  (a*(b*x^2-1)^2-(a-1))
  // Where 'a=1/(2*b-b^2)' and 'b' moves around the negative lobe.
  float wB=float(2.0/5.0)*d2+float(-1.0);
  float wA=lob*d2+float(-1.0);
  wB*=wB;
  wA*=wA;
  wB=float(25.0/16.0)*wB+float(-(25.0/16.0-1.0));
  float w=wB*wA;
  // Do weighted average.
  aC+=c*w;aW+=w;}
//------------------------------------------------------------------------------------------------------------------------------
 // Accumulate direction and length.
 void FsrEasuSetF(
 thread float2& dir,
 thread float& len,
 float2 pp,
 bool biS,bool biT,bool biU,bool biV,
 float lA,float lB,float lC,float lD,float lE){
  // Compute bilinear weight, branches factor out as predicates are compiler time immediates.
  //  s t
  //  u v
  float w = float(0.0);
  if(biS)w=(float(1.0)-pp.x)*(float(1.0)-pp.y);
  if(biT)w=           pp.x *(float(1.0)-pp.y);
  if(biU)w=(float(1.0)-pp.x)*           pp.y ;
  if(biV)w=           pp.x *           pp.y ;
  // Direction is the '+' diff.
  //    a
  //  b c d
  //    e
  // Then takes magnitude from abs average of both sides of 'c'.
  // Length converts gradient reversal to 0, smoothly to non-reversal at 1, shaped, then adding horz and vert terms.
  float dc=lD-lC;
  float cb=lC-lB;
  float lenX=max(abs(dc),abs(cb));
  lenX=APrxLoRcpF1(lenX);
  float dirX=lD-lB;
  dir.x+=dirX*w;
  lenX=ASatF1(abs(dirX)*lenX);
  lenX*=lenX;
  len+=lenX*w;
  // Repeat for the y axis.
  float ec=lE-lC;
  float ca=lC-lA;
  float lenY=max(abs(ec),abs(ca));
  lenY=APrxLoRcpF1(lenY);
  float dirY=lE-lA;
  dir.y+=dirY*w;
  lenY=ASatF1(abs(dirY)*lenY);
  lenY*=lenY;
  len+=lenY*w;}
//------------------------------------------------------------------------------------------------------------------------------
 void FsrEasuF(
 thread float3& pix,
 uint2 ip, // Integer pixel position in output.
 uint4 con0, // Constants generated by FsrEasuCon().
 uint4 con1,
 uint4 con2,
 uint4 con3){
//------------------------------------------------------------------------------------------------------------------------------
  // Get position of 'f'.
  float2 pp=float2(ip)*AF2_AU2(con0.xy)+AF2_AU2(con0.zw);
  float2 fp=floor(pp);
  pp-=fp;
//------------------------------------------------------------------------------------------------------------------------------
  // 12-tap kernel.
  //    b c
  //  e f g h
  //  i j k l
  //    n o
  // Gather 4 ordering.
  //  a b
  //  r g
  // For packed FP16, need either {rg} or {ab} so using the following setup for gather in all versions,
  //    a b    <- unused (z)
  //    r g
  //  a b a b
  //  r g r g
  //    a b
  //    r g    <- unused (z)
  // Allowing dead-code removal to remove the 'z's.
  float2 p0=fp*AF2_AU2(con1.xy)+AF2_AU2(con1.zw);
  // These are from p0 to avoid pulling two constants on pre-Navi hardware.
  float2 p1=p0+AF2_AU2(con2.xy);
  float2 p2=p0+AF2_AU2(con2.zw);
  float2 p3=p0+AF2_AU2(con3.xy);
  float4 bczzR=FsrEasuRF(p0);
  float4 bczzG=FsrEasuGF(p0);
  float4 bczzB=FsrEasuBF(p0);
  float4 ijfeR=FsrEasuRF(p1);
  float4 ijfeG=FsrEasuGF(p1);
  float4 ijfeB=FsrEasuBF(p1);
  float4 klhgR=FsrEasuRF(p2);
  float4 klhgG=FsrEasuGF(p2);
  float4 klhgB=FsrEasuBF(p2);
  float4 zzonR=FsrEasuRF(p3);
  float4 zzonG=FsrEasuGF(p3);
  float4 zzonB=FsrEasuBF(p3);
//------------------------------------------------------------------------------------------------------------------------------
  // Simplest multi-channel approximate luma possible (luma times 2, in 2 FMA/MAD).
  float4 bczzL=bczzB*float4(0.5)+(bczzR*float4(0.5)+bczzG);
  float4 ijfeL=ijfeB*float4(0.5)+(ijfeR*float4(0.5)+ijfeG);
  float4 klhgL=klhgB*float4(0.5)+(klhgR*float4(0.5)+klhgG);
  float4 zzonL=zzonB*float4(0.5)+(zzonR*float4(0.5)+zzonG);
  // Rename.
  float bL=bczzL.x;
  float cL=bczzL.y;
  float iL=ijfeL.x;
  float jL=ijfeL.y;
  float fL=ijfeL.z;
  float eL=ijfeL.w;
  float kL=klhgL.x;
  float lL=klhgL.y;
  float hL=klhgL.z;
  float gL=klhgL.w;
  float oL=zzonL.z;
  float nL=zzonL.w;
  // Accumulate for bilinear interpolation.
  float2 dir=float2(0.0);
  float len=float(0.0);
  FsrEasuSetF(dir,len,pp,true, false,false,false,bL,eL,fL,gL,jL);
  FsrEasuSetF(dir,len,pp,false,true ,false,false,cL,fL,gL,hL,kL);
  FsrEasuSetF(dir,len,pp,false,false,true ,false,fL,iL,jL,kL,nL);
  FsrEasuSetF(dir,len,pp,false,false,false,true ,gL,jL,kL,lL,oL);
//------------------------------------------------------------------------------------------------------------------------------
  // Normalize with approximation, and cleanup close to zero.
  float2 dir2=dir*dir;
  float dirR=dir2.x+dir2.y;
  bool zro=dirR<float(1.0/32768.0);
  dirR=APrxLoRsqF1(dirR);
  dirR=zro?float(1.0):dirR;
  dir.x=zro?float(1.0):dir.x;
  dir*=float2(dirR);
  // Transform from {0 to 2} to {0 to 1} range, and shape with square.
  len=len*float(0.5);
  len*=len;
  // Stretch kernel {1.0 vert|horz, to sqrt(2.0) on diagonal}.
  float stretch=(dir.x*dir.x+dir.y*dir.y)*APrxLoRcpF1(max(abs(dir.x),abs(dir.y)));
  // Anisotropic length after rotation,
  //  x := 1.0 lerp to 'stretch' on edges
  //  y := 1.0 lerp to 2x on edges
  float2 len2=float2(float(1.0)+(stretch-float(1.0))*len,float(1.0)+float(-0.5)*len);
  // Based on the amount of 'edge',
  // the window shifts from +/-{sqrt(2.0) to slightly beyond 2.0}.
  float lob=float(0.5)+float((1.0/4.0-0.04)-0.5)*len;
  // Set distance^2 clipping point to the end of the adjustable window.
  float clp=APrxLoRcpF1(lob);
//------------------------------------------------------------------------------------------------------------------------------
  // Accumulation mixed with min/max of 4 nearest.
  //    b c
  //  e f g h
  //  i j k l
  //    n o
  float3 min4=min(AMin3F3(float3(ijfeR.z,ijfeG.z,ijfeB.z),float3(klhgR.w,klhgG.w,klhgB.w),float3(ijfeR.y,ijfeG.y,ijfeB.y)),
               float3(klhgR.x,klhgG.x,klhgB.x));
  float3 max4=max(AMax3F3(float3(ijfeR.z,ijfeG.z,ijfeB.z),float3(klhgR.w,klhgG.w,klhgB.w),float3(ijfeR.y,ijfeG.y,ijfeB.y)),
               float3(klhgR.x,klhgG.x,klhgB.x));
  // Accumulation.
  float3 aC=float3(0.0);
  float aW=float(0.0);
  FsrEasuTapF(aC,aW,float2( 0.0,-1.0)-pp,dir,len2,lob,clp,float3(bczzR.x,bczzG.x,bczzB.x)); // b
  FsrEasuTapF(aC,aW,float2( 1.0,-1.0)-pp,dir,len2,lob,clp,float3(bczzR.y,bczzG.y,bczzB.y)); // c
  FsrEasuTapF(aC,aW,float2(-1.0, 1.0)-pp,dir,len2,lob,clp,float3(ijfeR.x,ijfeG.x,ijfeB.x)); // i
  FsrEasuTapF(aC,aW,float2( 0.0, 1.0)-pp,dir,len2,lob,clp,float3(ijfeR.y,ijfeG.y,ijfeB.y)); // j
  FsrEasuTapF(aC,aW,float2( 0.0, 0.0)-pp,dir,len2,lob,clp,float3(ijfeR.z,ijfeG.z,ijfeB.z)); // f
  FsrEasuTapF(aC,aW,float2(-1.0, 0.0)-pp,dir,len2,lob,clp,float3(ijfeR.w,ijfeG.w,ijfeB.w)); // e
  FsrEasuTapF(aC,aW,float2( 1.0, 1.0)-pp,dir,len2,lob,clp,float3(klhgR.x,klhgG.x,klhgB.x)); // k
  FsrEasuTapF(aC,aW,float2( 2.0, 1.0)-pp,dir,len2,lob,clp,float3(klhgR.y,klhgG.y,klhgB.y)); // l
  FsrEasuTapF(aC,aW,float2( 2.0, 0.0)-pp,dir,len2,lob,clp,float3(klhgR.z,klhgG.z,klhgB.z)); // h
  FsrEasuTapF(aC,aW,float2( 1.0, 0.0)-pp,dir,len2,lob,clp,float3(klhgR.w,klhgG.w,klhgB.w)); // g
  FsrEasuTapF(aC,aW,float2( 1.0, 2.0)-pp,dir,len2,lob,clp,float3(zzonR.z,zzonG.z,zzonB.z)); // o
  FsrEasuTapF(aC,aW,float2( 0.0, 2.0)-pp,dir,len2,lob,clp,float3(zzonR.w,zzonG.w,zzonB.w)); // n
//------------------------------------------------------------------------------------------------------------------------------
  // Normalize and dering.
  pix=min(max4,max(min4,aC*float3(ARcpF1(aW))));}
 void FsrRcasF(
 thread float& pixR, // Output values, non-vector so port between RcasFilter() and RcasFilterH() is easy.
 thread float& pixG,
 thread float& pixB,
 uint2 ip, // Integer pixel position in output.
 uint4 con){ // Constant generated by RcasSetup().
  // Algorithm uses minimal 3x3 pixel neighborhood.
  //    b 
  //  d e f
  //    h
  int2 sp=int2(ip);
  float3 b=FsrRcasLoadF(sp+int2( 0,-1)).rgb;
  float3 d=FsrRcasLoadF(sp+int2(-1, 0)).rgb;
   float3 e=FsrRcasLoadF(sp).rgb;
  float3 f=FsrRcasLoadF(sp+int2( 1, 0)).rgb;
  float3 h=FsrRcasLoadF(sp+int2( 0, 1)).rgb;
  // Rename (32-bit) or regroup (16-bit).
  float bR=b.r;
  float bG=b.g;
  float bB=b.b;
  float dR=d.r;
  float dG=d.g;
  float dB=d.b;
  float eR=e.r;
  float eG=e.g;
  float eB=e.b;
  float fR=f.r;
  float fG=f.g;
  float fB=f.b;
  float hR=h.r;
  float hG=h.g;
  float hB=h.b;
  // Run optional input transform.
  FsrRcasInputF(bR,bG,bB);
  FsrRcasInputF(dR,dG,dB);
  FsrRcasInputF(eR,eG,eB);
  FsrRcasInputF(fR,fG,fB);
  FsrRcasInputF(hR,hG,hB);
  // Luma times 2.
  float bL=bB*float(0.5)+(bR*float(0.5)+bG);
  float dL=dB*float(0.5)+(dR*float(0.5)+dG);
  float eL=eB*float(0.5)+(eR*float(0.5)+eG);
  float fL=fB*float(0.5)+(fR*float(0.5)+fG);
  float hL=hB*float(0.5)+(hR*float(0.5)+hG);
  // Noise detection.
  float nz=float(0.25)*bL+float(0.25)*dL+float(0.25)*fL+float(0.25)*hL-eL;
  nz=ASatF1(abs(nz)*APrxMedRcpF1(AMax3F1(AMax3F1(bL,dL,eL),fL,hL)-AMin3F1(AMin3F1(bL,dL,eL),fL,hL)));
  nz=float(-0.5)*nz+float(1.0);
  // Min and max of ring.
  float mn4R=min(AMin3F1(bR,dR,fR),hR);
  float mn4G=min(AMin3F1(bG,dG,fG),hG);
  float mn4B=min(AMin3F1(bB,dB,fB),hB);
  float mx4R=max(AMax3F1(bR,dR,fR),hR);
  float mx4G=max(AMax3F1(bG,dG,fG),hG);
  float mx4B=max(AMax3F1(bB,dB,fB),hB);
  // Immediate constants for peak range.
  float2 peakC=float2(1.0,-1.0*4.0);
  // Limiters, these need to be high precision RCPs.
  float hitMinR=min(mn4R,eR)*ARcpF1(float(4.0)*mx4R);
  float hitMinG=min(mn4G,eG)*ARcpF1(float(4.0)*mx4G);
  float hitMinB=min(mn4B,eB)*ARcpF1(float(4.0)*mx4B);
  float hitMaxR=(peakC.x-max(mx4R,eR))*ARcpF1(float(4.0)*mn4R+peakC.y);
  float hitMaxG=(peakC.x-max(mx4G,eG))*ARcpF1(float(4.0)*mn4G+peakC.y);
  float hitMaxB=(peakC.x-max(mx4B,eB))*ARcpF1(float(4.0)*mn4B+peakC.y);
  float lobeR=max(-hitMinR,hitMaxR);
  float lobeG=max(-hitMinG,hitMaxG);
  float lobeB=max(-hitMinB,hitMaxB);
  float lobe=max(float(-FSR_RCAS_LIMIT),min(AMax3F1(lobeR,lobeG,lobeB),float(0.0)))*AF1_AU1(con.x);
  // Apply noise removal.
   lobe*=nz;
  // Resolve, which needs the medium precision rcp approximation to avoid visible tonality changes.
  float rcpL=APrxMedRcpF1(float(4.0)*lobe+float(1.0));
  pixR=(lobe*bR+lobe*dR+lobe*hR+lobe*fR+eR)*rcpL;
  pixG=(lobe*bG+lobe*dG+lobe*hG+lobe*fG+eG)*rcpL;
  pixB=(lobe*bB+lobe*dB+lobe*hB+lobe*fB+eB)*rcpL;
  return;} 
};
kernel void fsrEasu(texture2d<float,access::read> src [[texture(0)]], texture2d<float,access::write> dst [[texture(1)]], uint2 p [[thread_position_in_grid]]) {
 if(any(p>=uint2(dst.get_width(),dst.get_height()))) return;
 float2 inv=1.0f/float2(src.get_width(),src.get_height());
 float2 scale=float2(src.get_width(),src.get_height())/float2(dst.get_width(),dst.get_height());
 uint4 c0=as_type<uint4>(float4(scale,0.5f*scale-0.5f));
 uint4 c1=as_type<uint4>(float4(inv,inv*float2(1,-1)));
 uint4 c2=as_type<uint4>(float4(inv*float2(-1,2),inv*float2(1,2)));
 uint4 c3=as_type<uint4>(float4(inv*float2(0,4),0,0));
 FSR f={src}; float3 rgb; f.FsrEasuF(rgb,p,c0,c1,c2,c3);
 dst.write(float4(clamp(rgb,0.0f,1.0f),1),p);
}
kernel void fsrRcas(texture2d<float,access::read> src [[texture(0)]], texture2d<float,access::write> dst [[texture(1)]], constant float& sharpness [[buffer(0)]], uint2 p [[thread_position_in_grid]]) {
 if(any(p>=uint2(dst.get_width(),dst.get_height()))) return;
 FSR f={src}; float3 rgb; uint4 c=uint4(as_type<uint>(exp2(-2.0f*(1.0f-sharpness))),0,0,0);
 float r,g,b; f.FsrRcasF(r,g,b,p,c); rgb=float3(r,g,b);
 dst.write(float4(clamp(rgb,0.0f,1.0f),1),p);
}
