// The MIT License(MIT)
//
// Copyright(c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files(the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and / or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions :
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE AUTHORS OR
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
// IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

// Generated by BuildScripts/generate-nis-metal.py; do not edit.

#include <metal_stdlib>
using namespace metal;
#define NIS_SCALER 1
#define NIS_BLOCK_WIDTH 32
#define NIS_BLOCK_HEIGHT 16
#define NIS_THREAD_GROUP_SIZE 128
#define NIS_VIEWPORT_SUPPORT 1
#define NIS_TEXTURE_GATHER 0
#define NIS_NV12_SUPPORT 0
#define NIS_HDR_MODE_NONE 0
#define NIS_HDR_MODE_LINEAR 1
#define NIS_HDR_MODE_PQ 2
#define kHDRCompressionFactor 0.282842712f
#define NIS_UNROLL
#define NIS_UNROLL_INNER
#define NIS_SCALE_INT 1
#define NIS_SCALE_FLOAT 1.0f
#define NVF float
#define NVF2 float2
#define NVF3 float3
#define NVF4 float4
#define NVH float
#define NVH4 float4
#define NVI int
#define NVI2 int2
#define NVU uint
#define NVU2 uint2
#define NVB bool
#define lerp mix
#define NVTEX_SAMPLE(x, s, p) x.sample(s, p, level(0))
#define NVTEX_STORE(x, p, v) x.write(clamp(v, 0.0f, 1.0f), uint2(p))
#define NVCLAMP(x) (x)
#define GroupMemoryBarrierWithGroupSync() threadgroup_barrier(mem_flags::mem_threadgroup)
constexpr sampler samplerLinearClamp(coord::normalized, filter::linear, address::clamp_to_edge);

struct NISConfig {
    float kDetectRatio;
    float kDetectThres;
    float kMinContrastRatio;
    float kRatioNorm;

    float kContrastBoost;
    float kEps;
    float kSharpStartY;
    float kSharpScaleY;

    float kSharpStrengthMin;
    float kSharpStrengthScale;
    float kSharpLimitMin;
    float kSharpLimitScale;

    float kScaleX;
    float kScaleY;
    float kDstNormX;
    float kDstNormY;

    float kSrcNormX;
    float kSrcNormY;

    uint kInputViewportOriginX;
    uint kInputViewportOriginY;
    uint kInputViewportWidth;
    uint kInputViewportHeight;

    uint kOutputViewportOriginX;
    uint kOutputViewportOriginY;
    uint kOutputViewportWidth;
    uint kOutputViewportHeight;

    float reserved0;
    float reserved1;
};
constant float4 nisScaleCoefs[128] = {
    float4(0.0f, 0.0f, 1.0000f, 0.0f),
    float4(0.0f, 0.0f, 0.0f, 0.0f),
    float4(0.0029f, -0.0127f, 1.0000f, 0.0132f),
    float4(-0.0034f, 0.0f, 0.0f, 0.0f),
    float4(0.0063f, -0.0249f, 0.9985f, 0.0269f),
    float4(-0.0068f, 0.0f, 0.0f, 0.0f),
    float4(0.0088f, -0.0361f, 0.9956f, 0.0415f),
    float4(-0.0103f, 0.0005f, 0.0f, 0.0f),
    float4(0.0117f, -0.0474f, 0.9932f, 0.0562f),
    float4(-0.0142f, 0.0005f, 0.0f, 0.0f),
    float4(0.0142f, -0.0576f, 0.9897f, 0.0713f),
    float4(-0.0181f, 0.0005f, 0.0f, 0.0f),
    float4(0.0166f, -0.0674f, 0.9844f, 0.0874f),
    float4(-0.0220f, 0.0010f, 0.0f, 0.0f),
    float4(0.0186f, -0.0762f, 0.9785f, 0.1040f),
    float4(-0.0264f, 0.0015f, 0.0f, 0.0f),
    float4(0.0205f, -0.0850f, 0.9727f, 0.1206f),
    float4(-0.0308f, 0.0020f, 0.0f, 0.0f),
    float4(0.0225f, -0.0928f, 0.9648f, 0.1382f),
    float4(-0.0352f, 0.0024f, 0.0f, 0.0f),
    float4(0.0239f, -0.1006f, 0.9575f, 0.1558f),
    float4(-0.0396f, 0.0029f, 0.0f, 0.0f),
    float4(0.0254f, -0.1074f, 0.9487f, 0.1738f),
    float4(-0.0439f, 0.0034f, 0.0f, 0.0f),
    float4(0.0264f, -0.1138f, 0.9390f, 0.1929f),
    float4(-0.0488f, 0.0044f, 0.0f, 0.0f),
    float4(0.0278f, -0.1191f, 0.9282f, 0.2119f),
    float4(-0.0537f, 0.0049f, 0.0f, 0.0f),
    float4(0.0288f, -0.1245f, 0.9170f, 0.2310f),
    float4(-0.0581f, 0.0059f, 0.0f, 0.0f),
    float4(0.0293f, -0.1294f, 0.9058f, 0.2510f),
    float4(-0.0630f, 0.0063f, 0.0f, 0.0f),
    float4(0.0303f, -0.1333f, 0.8926f, 0.2710f),
    float4(-0.0679f, 0.0073f, 0.0f, 0.0f),
    float4(0.0308f, -0.1367f, 0.8789f, 0.2915f),
    float4(-0.0728f, 0.0083f, 0.0f, 0.0f),
    float4(0.0308f, -0.1401f, 0.8657f, 0.3120f),
    float4(-0.0776f, 0.0093f, 0.0f, 0.0f),
    float4(0.0313f, -0.1426f, 0.8506f, 0.3330f),
    float4(-0.0825f, 0.0103f, 0.0f, 0.0f),
    float4(0.0313f, -0.1445f, 0.8354f, 0.3540f),
    float4(-0.0874f, 0.0112f, 0.0f, 0.0f),
    float4(0.0313f, -0.1460f, 0.8193f, 0.3755f),
    float4(-0.0923f, 0.0122f, 0.0f, 0.0f),
    float4(0.0313f, -0.1470f, 0.8022f, 0.3965f),
    float4(-0.0967f, 0.0137f, 0.0f, 0.0f),
    float4(0.0308f, -0.1479f, 0.7856f, 0.4185f),
    float4(-0.1016f, 0.0146f, 0.0f, 0.0f),
    float4(0.0303f, -0.1479f, 0.7681f, 0.4399f),
    float4(-0.1060f, 0.0156f, 0.0f, 0.0f),
    float4(0.0298f, -0.1479f, 0.7505f, 0.4614f),
    float4(-0.1104f, 0.0166f, 0.0f, 0.0f),
    float4(0.0293f, -0.1470f, 0.7314f, 0.4829f),
    float4(-0.1147f, 0.0181f, 0.0f, 0.0f),
    float4(0.0288f, -0.1460f, 0.7119f, 0.5049f),
    float4(-0.1187f, 0.0190f, 0.0f, 0.0f),
    float4(0.0278f, -0.1445f, 0.6929f, 0.5264f),
    float4(-0.1226f, 0.0200f, 0.0f, 0.0f),
    float4(0.0273f, -0.1431f, 0.6724f, 0.5479f),
    float4(-0.1260f, 0.0215f, 0.0f, 0.0f),
    float4(0.0264f, -0.1411f, 0.6528f, 0.5693f),
    float4(-0.1299f, 0.0225f, 0.0f, 0.0f),
    float4(0.0254f, -0.1387f, 0.6323f, 0.5903f),
    float4(-0.1328f, 0.0234f, 0.0f, 0.0f),
    float4(0.0244f, -0.1357f, 0.6113f, 0.6113f),
    float4(-0.1357f, 0.0244f, 0.0f, 0.0f),
    float4(0.0234f, -0.1328f, 0.5903f, 0.6323f),
    float4(-0.1387f, 0.0254f, 0.0f, 0.0f),
    float4(0.0225f, -0.1299f, 0.5693f, 0.6528f),
    float4(-0.1411f, 0.0264f, 0.0f, 0.0f),
    float4(0.0215f, -0.1260f, 0.5479f, 0.6724f),
    float4(-0.1431f, 0.0273f, 0.0f, 0.0f),
    float4(0.0200f, -0.1226f, 0.5264f, 0.6929f),
    float4(-0.1445f, 0.0278f, 0.0f, 0.0f),
    float4(0.0190f, -0.1187f, 0.5049f, 0.7119f),
    float4(-0.1460f, 0.0288f, 0.0f, 0.0f),
    float4(0.0181f, -0.1147f, 0.4829f, 0.7314f),
    float4(-0.1470f, 0.0293f, 0.0f, 0.0f),
    float4(0.0166f, -0.1104f, 0.4614f, 0.7505f),
    float4(-0.1479f, 0.0298f, 0.0f, 0.0f),
    float4(0.0156f, -0.1060f, 0.4399f, 0.7681f),
    float4(-0.1479f, 0.0303f, 0.0f, 0.0f),
    float4(0.0146f, -0.1016f, 0.4185f, 0.7856f),
    float4(-0.1479f, 0.0308f, 0.0f, 0.0f),
    float4(0.0137f, -0.0967f, 0.3965f, 0.8022f),
    float4(-0.1470f, 0.0313f, 0.0f, 0.0f),
    float4(0.0122f, -0.0923f, 0.3755f, 0.8193f),
    float4(-0.1460f, 0.0313f, 0.0f, 0.0f),
    float4(0.0112f, -0.0874f, 0.3540f, 0.8354f),
    float4(-0.1445f, 0.0313f, 0.0f, 0.0f),
    float4(0.0103f, -0.0825f, 0.3330f, 0.8506f),
    float4(-0.1426f, 0.0313f, 0.0f, 0.0f),
    float4(0.0093f, -0.0776f, 0.3120f, 0.8657f),
    float4(-0.1401f, 0.0308f, 0.0f, 0.0f),
    float4(0.0083f, -0.0728f, 0.2915f, 0.8789f),
    float4(-0.1367f, 0.0308f, 0.0f, 0.0f),
    float4(0.0073f, -0.0679f, 0.2710f, 0.8926f),
    float4(-0.1333f, 0.0303f, 0.0f, 0.0f),
    float4(0.0063f, -0.0630f, 0.2510f, 0.9058f),
    float4(-0.1294f, 0.0293f, 0.0f, 0.0f),
    float4(0.0059f, -0.0581f, 0.2310f, 0.9170f),
    float4(-0.1245f, 0.0288f, 0.0f, 0.0f),
    float4(0.0049f, -0.0537f, 0.2119f, 0.9282f),
    float4(-0.1191f, 0.0278f, 0.0f, 0.0f),
    float4(0.0044f, -0.0488f, 0.1929f, 0.9390f),
    float4(-0.1138f, 0.0264f, 0.0f, 0.0f),
    float4(0.0034f, -0.0439f, 0.1738f, 0.9487f),
    float4(-0.1074f, 0.0254f, 0.0f, 0.0f),
    float4(0.0029f, -0.0396f, 0.1558f, 0.9575f),
    float4(-0.1006f, 0.0239f, 0.0f, 0.0f),
    float4(0.0024f, -0.0352f, 0.1382f, 0.9648f),
    float4(-0.0928f, 0.0225f, 0.0f, 0.0f),
    float4(0.0020f, -0.0308f, 0.1206f, 0.9727f),
    float4(-0.0850f, 0.0205f, 0.0f, 0.0f),
    float4(0.0015f, -0.0264f, 0.1040f, 0.9785f),
    float4(-0.0762f, 0.0186f, 0.0f, 0.0f),
    float4(0.0010f, -0.0220f, 0.0874f, 0.9844f),
    float4(-0.0674f, 0.0166f, 0.0f, 0.0f),
    float4(0.0005f, -0.0181f, 0.0713f, 0.9897f),
    float4(-0.0576f, 0.0142f, 0.0f, 0.0f),
    float4(0.0005f, -0.0142f, 0.0562f, 0.9932f),
    float4(-0.0474f, 0.0117f, 0.0f, 0.0f),
    float4(0.0005f, -0.0103f, 0.0415f, 0.9956f),
    float4(-0.0361f, 0.0088f, 0.0f, 0.0f),
    float4(0.0f, -0.0068f, 0.0269f, 0.9985f),
    float4(-0.0249f, 0.0063f, 0.0f, 0.0f),
    float4(0.0f, -0.0034f, 0.0132f, 1.0000f),
    float4(-0.0127f, 0.0029f, 0.0f, 0.0f)
};
constant float4 nisUSM[128] = {
    float4(0.0f, -0.6001f, 1.2002f, -0.6001f),
    float4(0.0f, 0.0f, 0.0f, 0.0f),
    float4(0.0029f, -0.6084f, 1.1987f, -0.5903f),
    float4(-0.0029f, 0.0f, 0.0f, 0.0f),
    float4(0.0049f, -0.6147f, 1.1958f, -0.5791f),
    float4(-0.0068f, 0.0005f, 0.0f, 0.0f),
    float4(0.0073f, -0.6196f, 1.1890f, -0.5659f),
    float4(-0.0103f, 0.0f, 0.0f, 0.0f),
    float4(0.0093f, -0.6235f, 1.1802f, -0.5513f),
    float4(-0.0151f, 0.0f, 0.0f, 0.0f),
    float4(0.0112f, -0.6265f, 1.1699f, -0.5352f),
    float4(-0.0195f, 0.0005f, 0.0f, 0.0f),
    float4(0.0122f, -0.6270f, 1.1582f, -0.5181f),
    float4(-0.0259f, 0.0005f, 0.0f, 0.0f),
    float4(0.0142f, -0.6284f, 1.1455f, -0.5005f),
    float4(-0.0317f, 0.0005f, 0.0f, 0.0f),
    float4(0.0156f, -0.6265f, 1.1274f, -0.4790f),
    float4(-0.0386f, 0.0005f, 0.0f, 0.0f),
    float4(0.0166f, -0.6235f, 1.1089f, -0.4570f),
    float4(-0.0454f, 0.0010f, 0.0f, 0.0f),
    float4(0.0176f, -0.6187f, 1.0879f, -0.4346f),
    float4(-0.0532f, 0.0010f, 0.0f, 0.0f),
    float4(0.0181f, -0.6138f, 1.0659f, -0.4102f),
    float4(-0.0615f, 0.0015f, 0.0f, 0.0f),
    float4(0.0190f, -0.6069f, 1.0405f, -0.3843f),
    float4(-0.0698f, 0.0015f, 0.0f, 0.0f),
    float4(0.0195f, -0.6006f, 1.0161f, -0.3574f),
    float4(-0.0796f, 0.0020f, 0.0f, 0.0f),
    float4(0.0200f, -0.5928f, 0.9893f, -0.3286f),
    float4(-0.0898f, 0.0024f, 0.0f, 0.0f),
    float4(0.0200f, -0.5820f, 0.9580f, -0.2988f),
    float4(-0.1001f, 0.0029f, 0.0f, 0.0f),
    float4(0.0200f, -0.5728f, 0.9292f, -0.2690f),
    float4(-0.1104f, 0.0034f, 0.0f, 0.0f),
    float4(0.0200f, -0.5620f, 0.8975f, -0.2368f),
    float4(-0.1226f, 0.0039f, 0.0f, 0.0f),
    float4(0.0205f, -0.5498f, 0.8643f, -0.2046f),
    float4(-0.1343f, 0.0044f, 0.0f, 0.0f),
    float4(0.0200f, -0.5371f, 0.8301f, -0.1709f),
    float4(-0.1465f, 0.0049f, 0.0f, 0.0f),
    float4(0.0195f, -0.5239f, 0.7944f, -0.1367f),
    float4(-0.1587f, 0.0054f, 0.0f, 0.0f),
    float4(0.0195f, -0.5107f, 0.7598f, -0.1021f),
    float4(-0.1724f, 0.0059f, 0.0f, 0.0f),
    float4(0.0190f, -0.4966f, 0.7231f, -0.0649f),
    float4(-0.1865f, 0.0063f, 0.0f, 0.0f),
    float4(0.0186f, -0.4819f, 0.6846f, -0.0288f),
    float4(-0.1997f, 0.0068f, 0.0f, 0.0f),
    float4(0.0186f, -0.4668f, 0.6460f, 0.0093f),
    float4(-0.2144f, 0.0073f, 0.0f, 0.0f),
    float4(0.0176f, -0.4507f, 0.6055f, 0.0479f),
    float4(-0.2290f, 0.0083f, 0.0f, 0.0f),
    float4(0.0171f, -0.4370f, 0.5693f, 0.0859f),
    float4(-0.2446f, 0.0088f, 0.0f, 0.0f),
    float4(0.0161f, -0.4199f, 0.5283f, 0.1255f),
    float4(-0.2598f, 0.0098f, 0.0f, 0.0f),
    float4(0.0161f, -0.4048f, 0.4883f, 0.1655f),
    float4(-0.2754f, 0.0103f, 0.0f, 0.0f),
    float4(0.0151f, -0.3887f, 0.4497f, 0.2041f),
    float4(-0.2910f, 0.0107f, 0.0f, 0.0f),
    float4(0.0142f, -0.3711f, 0.4072f, 0.2446f),
    float4(-0.3066f, 0.0117f, 0.0f, 0.0f),
    float4(0.0137f, -0.3555f, 0.3672f, 0.2852f),
    float4(-0.3228f, 0.0122f, 0.0f, 0.0f),
    float4(0.0132f, -0.3394f, 0.3262f, 0.3262f),
    float4(-0.3394f, 0.0132f, 0.0f, 0.0f),
    float4(0.0122f, -0.3228f, 0.2852f, 0.3672f),
    float4(-0.3555f, 0.0137f, 0.0f, 0.0f),
    float4(0.0117f, -0.3066f, 0.2446f, 0.4072f),
    float4(-0.3711f, 0.0142f, 0.0f, 0.0f),
    float4(0.0107f, -0.2910f, 0.2041f, 0.4497f),
    float4(-0.3887f, 0.0151f, 0.0f, 0.0f),
    float4(0.0103f, -0.2754f, 0.1655f, 0.4883f),
    float4(-0.4048f, 0.0161f, 0.0f, 0.0f),
    float4(0.0098f, -0.2598f, 0.1255f, 0.5283f),
    float4(-0.4199f, 0.0161f, 0.0f, 0.0f),
    float4(0.0088f, -0.2446f, 0.0859f, 0.5693f),
    float4(-0.4370f, 0.0171f, 0.0f, 0.0f),
    float4(0.0083f, -0.2290f, 0.0479f, 0.6055f),
    float4(-0.4507f, 0.0176f, 0.0f, 0.0f),
    float4(0.0073f, -0.2144f, 0.0093f, 0.6460f),
    float4(-0.4668f, 0.0186f, 0.0f, 0.0f),
    float4(0.0068f, -0.1997f, -0.0288f, 0.6846f),
    float4(-0.4819f, 0.0186f, 0.0f, 0.0f),
    float4(0.0063f, -0.1865f, -0.0649f, 0.7231f),
    float4(-0.4966f, 0.0190f, 0.0f, 0.0f),
    float4(0.0059f, -0.1724f, -0.1021f, 0.7598f),
    float4(-0.5107f, 0.0195f, 0.0f, 0.0f),
    float4(0.0054f, -0.1587f, -0.1367f, 0.7944f),
    float4(-0.5239f, 0.0195f, 0.0f, 0.0f),
    float4(0.0049f, -0.1465f, -0.1709f, 0.8301f),
    float4(-0.5371f, 0.0200f, 0.0f, 0.0f),
    float4(0.0044f, -0.1343f, -0.2046f, 0.8643f),
    float4(-0.5498f, 0.0205f, 0.0f, 0.0f),
    float4(0.0039f, -0.1226f, -0.2368f, 0.8975f),
    float4(-0.5620f, 0.0200f, 0.0f, 0.0f),
    float4(0.0034f, -0.1104f, -0.2690f, 0.9292f),
    float4(-0.5728f, 0.0200f, 0.0f, 0.0f),
    float4(0.0029f, -0.1001f, -0.2988f, 0.9580f),
    float4(-0.5820f, 0.0200f, 0.0f, 0.0f),
    float4(0.0024f, -0.0898f, -0.3286f, 0.9893f),
    float4(-0.5928f, 0.0200f, 0.0f, 0.0f),
    float4(0.0020f, -0.0796f, -0.3574f, 1.0161f),
    float4(-0.6006f, 0.0195f, 0.0f, 0.0f),
    float4(0.0015f, -0.0698f, -0.3843f, 1.0405f),
    float4(-0.6069f, 0.0190f, 0.0f, 0.0f),
    float4(0.0015f, -0.0615f, -0.4102f, 1.0659f),
    float4(-0.6138f, 0.0181f, 0.0f, 0.0f),
    float4(0.0010f, -0.0532f, -0.4346f, 1.0879f),
    float4(-0.6187f, 0.0176f, 0.0f, 0.0f),
    float4(0.0010f, -0.0454f, -0.4570f, 1.1089f),
    float4(-0.6235f, 0.0166f, 0.0f, 0.0f),
    float4(0.0005f, -0.0386f, -0.4790f, 1.1274f),
    float4(-0.6265f, 0.0156f, 0.0f, 0.0f),
    float4(0.0005f, -0.0317f, -0.5005f, 1.1455f),
    float4(-0.6284f, 0.0142f, 0.0f, 0.0f),
    float4(0.0005f, -0.0259f, -0.5181f, 1.1582f),
    float4(-0.6270f, 0.0122f, 0.0f, 0.0f),
    float4(0.0005f, -0.0195f, -0.5352f, 1.1699f),
    float4(-0.6265f, 0.0112f, 0.0f, 0.0f),
    float4(0.0f, -0.0151f, -0.5513f, 1.1802f),
    float4(-0.6235f, 0.0093f, 0.0f, 0.0f),
    float4(0.0f, -0.0103f, -0.5659f, 1.1890f),
    float4(-0.6196f, 0.0073f, 0.0f, 0.0f),
    float4(0.0005f, -0.0068f, -0.5791f, 1.1958f),
    float4(-0.6147f, 0.0049f, 0.0f, 0.0f),
    float4(0.0f, -0.0029f, -0.5903f, 1.1987f),
    float4(-0.6084f, 0.0029f, 0.0f, 0.0f)
};

struct NISShared {
    float shPixelsY[38 * 22];
    float shCoefScaler[64][6];
    float shCoefUSM[64][6];
    float4 shEdgeMap[34 * 18];
};
struct NISShader {
    constant NISConfig &config;
    threadgroup NISShared &shared;
    texture2d<float> in_texture;
    texture2d<float, access::write> out_texture;
NVF getY(NVF3 rgba)
{
#if NIS_HDR_MODE == NIS_HDR_MODE_PQ
    return NVF(0.262f) * rgba.x + NVF(0.678f) * rgba.y + NVF(0.0593f) * rgba.z;
#elif NIS_HDR_MODE == NIS_HDR_MODE_LINEAR
    return sqrt(NVF(0.2126f) * rgba.x + NVF(0.7152f) * rgba.y + NVF(0.0722f) * rgba.z) * kHDRCompressionFactor;
#else
    return NVF(0.2126f) * rgba.x + NVF(0.7152f) * rgba.y + NVF(0.0722f) * rgba.z;
#endif
}

NVF getYLinear(NVF3 rgba)
{
    return NVF(0.2126f) * rgba.x + NVF(0.7152f) * rgba.y + NVF(0.0722f) * rgba.z;
}

NVF3 YUVtoRGB(NVF3 yuv)
{
    float y = yuv.x - 16.0f / 255.0f;
    float u = yuv.y - 128.0f / 255.0f;
    float v = yuv.z - 128.0f / 255.0f;
    NVF3 rgb;
    rgb.x = saturate(1.164f * y + 1.596f * v);
    rgb.y = saturate(1.164f * y - 0.392f * u - 0.813f * v);
    rgb.z = saturate(1.164f * y + 2.017f * u);
    return rgb;
}

#if NIS_SCALER
NVF4 GetEdgeMap(thread NVF (&p)[4][4], NVI i, NVI j)
#else
NVF4 GetEdgeMap(thread NVF (&p)[5][5], NVI i, NVI j)
#endif
{
    const NVF g_0 = abs(p[0 + i][0 + j] + p[0 + i][1 + j] + p[0 + i][2 + j] - p[2 + i][0 + j] - p[2 + i][1 + j] - p[2 + i][2 + j]);
    const NVF g_45 = abs(p[1 + i][0 + j] + p[0 + i][0 + j] + p[0 + i][1 + j] - p[2 + i][1 + j] - p[2 + i][2 + j] - p[1 + i][2 + j]);
    const NVF g_90 = abs(p[0 + i][0 + j] + p[1 + i][0 + j] + p[2 + i][0 + j] - p[0 + i][2 + j] - p[1 + i][2 + j] - p[2 + i][2 + j]);
    const NVF g_135 = abs(p[1 + i][0 + j] + p[2 + i][0 + j] + p[2 + i][1 + j] - p[0 + i][1 + j] - p[0 + i][2 + j] - p[1 + i][2 + j]);

    const NVF g_0_90_max = max(g_0, g_90);
    const NVF g_0_90_min = min(g_0, g_90);
    const NVF g_45_135_max = max(g_45, g_135);
    const NVF g_45_135_min = min(g_45, g_135);

    NVF e_0_90 = 0;
    NVF e_45_135 = 0;

    if (g_0_90_max + g_45_135_max == 0)
    {
        return NVF4(0, 0, 0, 0);
    }

    e_0_90 = min(g_0_90_max / (g_0_90_max + g_45_135_max), 1.0f);
    e_45_135 = 1.0f - e_0_90;

    NVB c_0_90 = (g_0_90_max > (g_0_90_min * config.kDetectRatio)) && (g_0_90_max > config.kDetectThres) && (g_0_90_max > g_45_135_min);
    NVB c_45_135 = (g_45_135_max > (g_45_135_min * config.kDetectRatio)) && (g_45_135_max > config.kDetectThres) && (g_45_135_max > g_0_90_min);
    NVB c_g_0_90 = g_0_90_max == g_0;
    NVB c_g_45_135 = g_45_135_max == g_45;

    NVF f_e_0_90 = (c_0_90 && c_45_135) ? e_0_90 : 1.0f;
    NVF f_e_45_135 = (c_0_90 && c_45_135) ? e_45_135 : 1.0f;

    NVF weight_0 = (c_0_90 && c_g_0_90) ? f_e_0_90 : 0.0f;
    NVF weight_90 = (c_0_90 && !c_g_0_90) ? f_e_0_90 : 0.0f;
    NVF weight_45 = (c_45_135 && c_g_45_135) ? f_e_45_135 : 0.0f;
    NVF weight_135 = (c_45_135 && !c_g_45_135) ? f_e_45_135 : 0.0f;

    return NVF4(weight_0, weight_90, weight_45, weight_135);
}

#if NIS_SCALER

#ifndef NIS_BLOCK_WIDTH
#define NIS_BLOCK_WIDTH 32
#endif
#ifndef NIS_BLOCK_HEIGHT
#define NIS_BLOCK_HEIGHT 24
#endif
#ifndef NIS_THREAD_GROUP_SIZE
#define NIS_THREAD_GROUP_SIZE 256
#endif
#define kPhaseCount  64
#define kFilterSize  6
#define kSupportSize 6
#define kPadSize     kSupportSize
// 'Tile' is the region of source luminance values that we load into shared.shPixelsY.
// It is the area of source pixels covered by the destination 'Block' plus a
// 3 pixel border of support pixels.
#define kTilePitch              (NIS_BLOCK_WIDTH + kPadSize)
#define kTileSize               (kTilePitch * (NIS_BLOCK_HEIGHT + kPadSize))
// 'EdgeMap' is the region of source pixels for which edge map vectors are derived.
// It is the area of source pixels covered by the destination 'Block' plus a
// 1 pixel border.
#define kEdgeMapPitch           (NIS_BLOCK_WIDTH + 2)
#define kEdgeMapSize            (kEdgeMapPitch * (NIS_BLOCK_HEIGHT + 2))






void LoadFilterBanksSh(NVI i0) {
    // Load up filter banks to shared memory
    // The work is spread over (kPhaseCount * 2) threads
    NVI i = i0;
#if( kPhaseCount * 2 > NIS_THREAD_GROUP_SIZE )
    for (; i < kPhaseCount * 2; i += NIS_THREAD_GROUP_SIZE)
#else
    if (i < kPhaseCount * 2)
#endif
    {
        NVI phase = i >> 1;
        NVI vIdx = i & 1;

        NVH4 v = NVH4(nisScaleCoefs[phase * 2 + vIdx]);
        NVI filterOffset = vIdx * 4;
        shared.shCoefScaler[phase][filterOffset + 0] = v.x;
        shared.shCoefScaler[phase][filterOffset + 1] = v.y;
        if (vIdx == 0)
        {
            shared.shCoefScaler[phase][2] = v.z;
            shared.shCoefScaler[phase][3] = v.w;
        }

        v = NVH4(nisUSM[phase * 2 + vIdx]);
        shared.shCoefUSM[phase][filterOffset + 0] = v.x;
        shared.shCoefUSM[phase][filterOffset + 1] = v.y;
        if (vIdx == 0)
        {
            shared.shCoefUSM[phase][2] = v.z;
            shared.shCoefUSM[phase][3] = v.w;
        }
    }
}


NVF CalcLTI(NVF p0, NVF p1, NVF p2, NVF p3, NVF p4, NVF p5, NVI phase_index)
{
    const NVB selector = (phase_index <= kPhaseCount / 2);
    NVF sel = selector ? p0 : p3;
    const NVF a_min = min(min(p1, p2), sel);
    const NVF a_max = max(max(p1, p2), sel);
    sel = selector ? p2 : p5;
    const NVF b_min = min(min(p3, p4), sel);
    const NVF b_max = max(max(p3, p4), sel);

    const NVF a_cont = a_max - a_min;
    const NVF b_cont = b_max - b_min;

    const NVF cont_ratio = max(a_cont, b_cont) / (min(a_cont, b_cont) + config.kEps);
    return (1.0f - saturate((cont_ratio - config.kMinContrastRatio) * config.kRatioNorm)) * config.kContrastBoost;
}

NVF4 GetInterpEdgeMap(thread const NVF4 (&edge)[2][2], NVF phase_frac_x, NVF phase_frac_y)
{
    NVF4 h0 = lerp(edge[0][0], edge[0][1], phase_frac_x);
    NVF4 h1 = lerp(edge[1][0], edge[1][1], phase_frac_x);
    return lerp(h0, h1, phase_frac_y);
}

NVF EvalPoly6(thread const NVF (&pxl)[6], NVI phase_int)
{
    NVF y = 0.f;
    {
        NIS_UNROLL
        for (NVI i = 0; i < 6; ++i)
        {
            y += shared.shCoefScaler[phase_int][i] * pxl[i];
        }
    }
    NVF y_usm = 0.f;
    {
        NIS_UNROLL
        for (NVI i = 0; i < 6; ++i)
        {
            y_usm += shared.shCoefUSM[phase_int][i] * pxl[i];
        }
    }

    // let's compute a piece-wise ramp based on luma
    const NVF y_scale = 1.0f - saturate((y * (1.0f / NIS_SCALE_FLOAT) - config.kSharpStartY) * config.kSharpScaleY);

    // scale the ramp to sharpen as a function of luma
    const NVF y_sharpness = y_scale * config.kSharpStrengthScale + config.kSharpStrengthMin;

    y_usm *= y_sharpness;

    // scale the ramp to limit USM as a function of luma
    const NVF y_sharpness_limit = (y_scale * config.kSharpLimitScale + config.kSharpLimitMin) * y;

    y_usm = min(y_sharpness_limit, max(-y_sharpness_limit, y_usm));
    // reduce ringing
    y_usm *= CalcLTI(pxl[0], pxl[1], pxl[2], pxl[3], pxl[4], pxl[5], phase_int);

    return y + y_usm;
}

NVF FilterNormal(thread const NVF (&p)[6][6], NVI phase_x_frac_int, NVI phase_y_frac_int)
{
    NVF h_acc = 0.0f;
    NIS_UNROLL
    for (NVI j = 0; j < 6; ++j)
    {
        NVF v_acc = 0.0f;
        NIS_UNROLL
        for (NVI i = 0; i < 6; ++i)
        {
            v_acc += p[i][j] * shared.shCoefScaler[phase_y_frac_int][i];
        }
        h_acc += v_acc * shared.shCoefScaler[phase_x_frac_int][j];
    }

    // let's return the sum unpacked -> we can accumulate it later
    return h_acc;
}

NVF AddDirFilters(thread NVF (&p)[6][6], NVF phase_x_frac, NVF phase_y_frac, NVI phase_x_frac_int, NVI phase_y_frac_int, NVF4 w)
{
    NVF f = 0;
    if (w.x > 0.0f)
    {
        // 0 deg filter
        NVF interp0Deg[6];
        {
            NIS_UNROLL
                for (NVI i = 0; i < 6; ++i)
                {
                    interp0Deg[i] = lerp(p[i][2], p[i][3], phase_x_frac);
                }
        }
        f += EvalPoly6(interp0Deg, phase_y_frac_int) * w.x;
    }
    if (w.y > 0.0f)
    {
        // 90 deg filter
        NVF interp90Deg[6];
        {
            NIS_UNROLL
                for (NVI i = 0; i < 6; ++i)
                {
                    interp90Deg[i] = lerp(p[2][i], p[3][i], phase_y_frac);
                }
        }

        f += EvalPoly6(interp90Deg, phase_x_frac_int) * w.y;
    }
    if (w.z > 0.0f)
    {
        //45 deg filter
        NVF pphase_b45 = 0.5f + 0.5f * (phase_x_frac - phase_y_frac);

        NVF temp_interp45Deg[7];
        temp_interp45Deg[1] = lerp(p[2][1], p[1][2], pphase_b45);
        temp_interp45Deg[3] = lerp(p[3][2], p[2][3], pphase_b45);
        temp_interp45Deg[5] = lerp(p[4][3], p[3][4], pphase_b45);
        {
            pphase_b45 = pphase_b45 - 0.5f;
            NVF a = (pphase_b45 >= 0.f) ? p[0][2] : p[2][0];
            NVF b = (pphase_b45 >= 0.f) ? p[1][3] : p[3][1];
            NVF c = (pphase_b45 >= 0.f) ? p[2][4] : p[4][2];
            NVF d = (pphase_b45 >= 0.f) ? p[3][5] : p[5][3];
            temp_interp45Deg[0] = lerp(p[1][1], a, abs(pphase_b45));
            temp_interp45Deg[2] = lerp(p[2][2], b, abs(pphase_b45));
            temp_interp45Deg[4] = lerp(p[3][3], c, abs(pphase_b45));
            temp_interp45Deg[6] = lerp(p[4][4], d, abs(pphase_b45));
        }

        NVF interp45Deg[6];
        NVF pphase_p45 = phase_x_frac + phase_y_frac;
        if (pphase_p45 >= 1)
        {
            NIS_UNROLL
                for (NVI i = 0; i < 6; i++)
                {
                    interp45Deg[i] = temp_interp45Deg[i + 1];
                }
            pphase_p45 = pphase_p45 - 1;
        }
        else
        {
            NIS_UNROLL
                for (NVI i = 0; i < 6; i++)
                {
                    interp45Deg[i] = temp_interp45Deg[i];
                }
        }

        f += EvalPoly6(interp45Deg, NVI(pphase_p45 * 64)) * w.z;
    }
    if (w.w > 0.0f)
    {
        //135 deg filter
        NVF pphase_b135 = 0.5f * (phase_x_frac + phase_y_frac);

        NVF temp_interp135Deg[7];
        temp_interp135Deg[1] = lerp(p[3][1], p[4][2], pphase_b135);
        temp_interp135Deg[3] = lerp(p[2][2], p[3][3], pphase_b135);
        temp_interp135Deg[5] = lerp(p[1][3], p[2][4], pphase_b135);
        {
            pphase_b135 = pphase_b135 - 0.5f;
            NVF a = (pphase_b135 >= 0.f) ? p[5][2] : p[3][0];
            NVF b = (pphase_b135 >= 0.f) ? p[4][3] : p[2][1];
            NVF c = (pphase_b135 >= 0.f) ? p[3][4] : p[1][2];
            NVF d = (pphase_b135 >= 0.f) ? p[2][5] : p[0][3];
            temp_interp135Deg[0] = lerp(p[4][1], a, abs(pphase_b135));
            temp_interp135Deg[2] = lerp(p[3][2], b, abs(pphase_b135));
            temp_interp135Deg[4] = lerp(p[2][3], c, abs(pphase_b135));
            temp_interp135Deg[6] = lerp(p[1][4], d, abs(pphase_b135));
        }

        NVF interp135Deg[6];
        NVF pphase_p135 = 1 + (phase_x_frac - phase_y_frac);
        if (pphase_p135 >= 1)
        {
            NIS_UNROLL
                for (NVI i = 0; i < 6; ++i)
                {
                    interp135Deg[i] = temp_interp135Deg[i + 1];
                }
            pphase_p135 = pphase_p135 - 1;
        }
        else
        {
            NIS_UNROLL
                for (NVI i = 0; i < 6; ++i)
                {
                    interp135Deg[i] = temp_interp135Deg[i];
                }
        }

        f += EvalPoly6(interp135Deg, NVI(pphase_p135 * 64)) * w.w;
    }
    return f;
}


//-----------------------------------------------------------------------------------------------
// NVScaler
//-----------------------------------------------------------------------------------------------
void NVScaler(NVU2 blockIdx, NVU threadIdx)
{
    // Figure out the range of pixels from input image that would be needed to be loaded for this thread-block
    NVI dstBlockX = NVI(NIS_BLOCK_WIDTH * blockIdx.x);
    NVI dstBlockY = NVI(NIS_BLOCK_HEIGHT * blockIdx.y);

    const NVI srcBlockStartX = NVI(floor((dstBlockX + 0.5f) * config.kScaleX - 0.5f));
    const NVI srcBlockStartY = NVI(floor((dstBlockY + 0.5f) * config.kScaleY - 0.5f));
    const NVI srcBlockEndX = NVI(ceil((dstBlockX + NIS_BLOCK_WIDTH + 0.5f) * config.kScaleX - 0.5f));
    const NVI srcBlockEndY = NVI(ceil((dstBlockY + NIS_BLOCK_HEIGHT + 0.5f) * config.kScaleY - 0.5f));

    NVI numTilePixelsX = srcBlockEndX - srcBlockStartX + kSupportSize - 1;
    NVI numTilePixelsY = srcBlockEndY - srcBlockStartY + kSupportSize - 1;

    // round-up load region to even size since we're loading in 2x2 batches
    numTilePixelsX += numTilePixelsX & 0x1;
    numTilePixelsY += numTilePixelsY & 0x1;
    const NVI numTilePixels = numTilePixelsX * numTilePixelsY;

    // calculate the equivalent values for the edge map
    const NVI numEdgeMapPixelsX = numTilePixelsX - kSupportSize + 2;
    const NVI numEdgeMapPixelsY = numTilePixelsY - kSupportSize + 2;
    const NVI numEdgeMapPixels = numEdgeMapPixelsX * numEdgeMapPixelsY;

    // fill in input luma tile (shared.shPixelsY) in batches of 2x2 pixels
    // we use texture gather to get extra support necessary
    // to compute 2x2 edge map outputs too
    {
        for (NVU i = threadIdx * 2; i < NVU(numTilePixels) >> 1; i += NIS_THREAD_GROUP_SIZE * 2)
        {
            NVU py = (i / numTilePixelsX) * 2;
            NVU px = i % numTilePixelsX;

            // 0.5 to be in the center of texel
            // - (kSupportSize - 1) / 2 to shift by the kernel support size
            NVF kShift = 0.5f - (kSupportSize - 1) / 2;
#if NIS_VIEWPORT_SUPPORT
            const NVF tx = (NVF(srcBlockStartX) + NVF(px) + NVF(config.kInputViewportOriginX) + kShift) * config.kSrcNormX;
            const NVF ty = (NVF(srcBlockStartY) + NVF(py) + NVF(config.kInputViewportOriginY) + kShift) * config.kSrcNormY;
#else
            const NVF tx = (srcBlockStartX + px + kShift) * config.kSrcNormX;
            const NVF ty = (srcBlockStartY + py + kShift) * config.kSrcNormY;
#endif
            NVF p[2][2];
#if NIS_TEXTURE_GATHER
            {
                const NVF4 sr = NVTEX_SAMPLE_RED(in_texture, samplerLinearClamp, NVF2(tx, ty));
                const NVF4 sg = NVTEX_SAMPLE_GREEN(in_texture, samplerLinearClamp, NVF2(tx, ty));
                const NVF4 sb = NVTEX_SAMPLE_BLUE(in_texture, samplerLinearClamp, NVF2(tx, ty));

                p[0][0] = getY(NVF3(sr.w, sg.w, sb.w));
                p[0][1] = getY(NVF3(sr.z, sg.z, sb.z));
                p[1][0] = getY(NVF3(sr.x, sg.x, sb.x));
                p[1][1] = getY(NVF3(sr.y, sg.y, sb.y));
            }
#else
            NIS_UNROLL_INNER
            for (NVI j = 0; j < 2; j++)
            {
                NIS_UNROLL_INNER
                for (NVI k = 0; k < 2; k++)
                {
#if NIS_NV12_SUPPORT
                    p[j][k] = NVTEX_SAMPLE(in_texture_y, samplerLinearClamp, NVF2(tx + k * config.kSrcNormX, ty + j * config.kSrcNormY));
#else
                    const NVF4 px = NVTEX_SAMPLE(in_texture, samplerLinearClamp, NVF2(tx + k * config.kSrcNormX, ty + j * config.kSrcNormY));
                    p[j][k] = getY(px.xyz);
#endif
                }
            }
#endif
            const NVU idx = py * kTilePitch + px;
            shared.shPixelsY[idx] = NVH(p[0][0]);
            shared.shPixelsY[idx + 1] = NVH(p[0][1]);
            shared.shPixelsY[idx + kTilePitch] = NVH(p[1][0]);
            shared.shPixelsY[idx + kTilePitch + 1] = NVH(p[1][1]);
        }
    }
    GroupMemoryBarrierWithGroupSync();
    {
        // fill in the edge map of 2x2 pixels
        for (NVU i = threadIdx * 2; i < NVU(numEdgeMapPixels) >> 1; i += NIS_THREAD_GROUP_SIZE * 2)
        {
            NVU py = (i / numEdgeMapPixelsX) * 2;
            NVU px = i % numEdgeMapPixelsX;

            const NVU edgeMapIdx = py * kEdgeMapPitch + px;

            NVU tileCornerIdx = (py + 1) * kTilePitch + px + 1;
            NVF p[4][4];
            NIS_UNROLL_INNER
            for (NVI j = 0; j < 4; j++)
            {
                NIS_UNROLL_INNER
                for (NVI k = 0; k < 4; k++)
                {
                    p[j][k] = shared.shPixelsY[tileCornerIdx + j * kTilePitch + k];
                }
            }

            shared.shEdgeMap[edgeMapIdx] = NVH4(GetEdgeMap(p, 0, 0));
            shared.shEdgeMap[edgeMapIdx + 1] = NVH4(GetEdgeMap(p, 0, 1));
            shared.shEdgeMap[edgeMapIdx + kEdgeMapPitch] = NVH4(GetEdgeMap(p, 1, 0));
            shared.shEdgeMap[edgeMapIdx + kEdgeMapPitch + 1] = NVH4(GetEdgeMap(p, 1, 1));
        }
    }
    LoadFilterBanksSh(NVI(threadIdx));
    GroupMemoryBarrierWithGroupSync();

    // output coord within a tile
    const NVI2 pos = NVI2(NVU(threadIdx) % NVU(NIS_BLOCK_WIDTH), NVU(threadIdx) / NVU(NIS_BLOCK_WIDTH));
    // x coord inside the output image
    const NVI dstX = dstBlockX + pos.x;
    // x coord inside the input image
    const NVF srcX = (0.5f + dstX) * config.kScaleX - 0.5f;
    // nearest integer part
    const NVI px = NVI(floor(srcX) - srcBlockStartX);
    // fractional part
    const NVF fx = srcX - floor(srcX);
    // discretized phase
    const NVI fx_int = NVI(fx * kPhaseCount);
#if NIS_VIEWPORT_SUPPORT
    if (NVU(dstX) >= config.kOutputViewportWidth)
    {
        return;
    }
#endif
    for (NVI k = 0; k < NIS_BLOCK_WIDTH * NIS_BLOCK_HEIGHT / NIS_THREAD_GROUP_SIZE; ++k)
    {
        // y coord inside the output image
        const NVI dstY = dstBlockY + pos.y + k * (NIS_THREAD_GROUP_SIZE / NIS_BLOCK_WIDTH);
        // y coord inside the input image
        const NVF srcY = (0.5f + dstY) * config.kScaleY - 0.5f;
#if NIS_VIEWPORT_SUPPORT
        if (!(NVU(dstY) >= config.kOutputViewportHeight))
#endif
        {
            // nearest integer part
            const NVI py = NVI(floor(srcY) - srcBlockStartY);
            // fractional part
            const NVF fy = srcY - floor(srcY);
            // discretized phase
            const NVI fy_int = NVI(fy * kPhaseCount);

            // generate weights for directional filters
            const NVI startEdgeMapIdx = py * kEdgeMapPitch + px;
            NVF4 edge[2][2];
            NIS_UNROLL
            for (NVI i = 0; i < 2; i++)
            {
                NIS_UNROLL
                for (NVI j = 0; j < 2; j++)
                {
                    // need to shift edge map sampling since it's a 2x2 centered inside 6x6 grid
                    edge[i][j] = shared.shEdgeMap[startEdgeMapIdx + (i * kEdgeMapPitch) + j];
                }
            }
            const NVF4 w = GetInterpEdgeMap(edge, fx, fy) * NIS_SCALE_INT;

            // load 6x6 support to regs
            const NVI startTileIdx = py * kTilePitch + px;
            NVF p[6][6];
            {
                NIS_UNROLL
                for (NVI i = 0; i < 6; ++i)
                {
                    NIS_UNROLL
                    for (NVI j = 0; j < 6; ++j)
                    {
                        p[i][j] = shared.shPixelsY[startTileIdx + i * kTilePitch + j];
                    }
                }
            }

            // weigth for luma
            const NVF baseWeight = NIS_SCALE_FLOAT - w.x - w.y - w.z - w.w;

            // final luma is a weighted product of directional & normal filters
            NVF opY = 0;

            // get traditional scaler filter output
            opY += FilterNormal(p, fx_int, fy_int) * baseWeight;

            // get directional filter bank output
            opY += AddDirFilters(p, fx, fy, fx_int, fy_int, w);

#if NIS_VIEWPORT_SUPPORT
            NVF2 coord = NVF2((srcX + config.kInputViewportOriginX + 0.5f) * config.kSrcNormX, (srcY + config.kInputViewportOriginY + 0.5f) * config.kSrcNormY);
            NVF2 dstCoord = NVF2(dstX + config.kOutputViewportOriginX, dstY + config.kOutputViewportOriginY);
#else
            NVF2 coord = NVF2((srcX + 0.5f) * config.kSrcNormX, (srcY + 0.5f) * config.kSrcNormY);
            NVF2 dstCoord = NVF2(dstX, dstY);
#endif
            // do bilinear tap for chroma upscaling
#if NIS_NV12_SUPPORT
            NVF y = NVTEX_SAMPLE(in_texture_y, samplerLinearClamp, coord);
            NVF2 uv = NVTEX_SAMPLE(in_texture_uv, samplerLinearClamp, coord);
            NVF4 op = NVF4(YUVtoRGB(NVF3(y, uv)), 1.0f);
#else
            NVF4 op = NVTEX_SAMPLE(in_texture, samplerLinearClamp, coord);
            NVF y = getY(NVF3(op.x, op.y, op.z));
#endif

#if NIS_HDR_MODE == NIS_HDR_MODE_LINEAR
            const NVF config.kEps = 1e-4f;
            const NVF kNorm = 1.0f / (NIS_SCALE_FLOAT * kHDRCompressionFactor);
            const NVF opYN = max(opY, 0.0f) * kNorm;
            const NVF corr = (opYN * opYN + config.kEps) / (max(getYLinear(NVF3(op.x, op.y, op.z)), 0.0f) + config.kEps);
            op.x *= corr;
            op.y *= corr;
            op.z *= corr;
#else
            const NVF corr = opY * (1.0f / NIS_SCALE_FLOAT) - y;
            op.x += corr;
            op.y += corr;
            op.z += corr;
#endif
            NVTEX_STORE(out_texture, dstCoord, NVCLAMP(op));
        }
    }
}
#endif
};
kernel void nisScale(texture2d<float> input [[texture(0)]],
                     texture2d<float, access::write> output [[texture(1)]],
                     constant NISConfig &config [[buffer(0)]],
                     uint2 group [[threadgroup_position_in_grid]],
                     uint lane [[thread_index_in_threadgroup]]) {
    threadgroup NISShared shared;
    NISShader shader{config, shared, input, output};
    shader.NVScaler(group, lane);
}
