#!/usr/bin/env python3
"""Reproduce the MSL adapter from NVIDIA's MIT-licensed NIS 1.0.3 sources."""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1] / "OpenNOWiOS/NIS"
scaler = (root / "NIS_Scaler.h").read_text()
config = (root / "NIS_Config.h").read_text()
license = scaler[:scaler.index("//---------------------------------------------------------------------------------")]
fields = re.search(r"struct NIS_ALIGNED\(256\) NISConfig\s*\{(.*?)\};", config, re.S)[1]
fields = fields.replace("uint32_t", "uint")
body = scaler[scaler.index("NVF getY("):scaler.index("#else\n\n#ifndef NIS_BLOCK_WIDTH", scaler.index("void NVScaler("))]
shared = re.findall(r"NVSHARED (.*?);", body)
body = re.sub(r"NVSHARED .*?;", "", body)
# Metal requires explicit address spaces for array-reference parameters.
body = re.sub(r"(const )?(NVF4|NVF) (\w+)((?:\[\d+\])+)(?=[,)])",
              lambda m: f"thread {m[1] or ''}{m[2]} (&{m[3]}){m[4]}", body)
for name in re.findall(r"(?:float|uint) (k\w+);", fields):
    body = re.sub(rf"\b{name}\b", "config." + name, body)
for declaration in shared:
    name = declaration.split()[1].split("[")[0]
    body = re.sub(rf"\b{name}\b", "shared." + name, body)
body = body.replace("NVTEX_LOAD(coef_scaler, NVI2(vIdx, phase))", "nisScaleCoefs[phase * 2 + vIdx]")
body = body.replace("NVTEX_LOAD(coef_usm, NVI2(vIdx, phase))", "nisUSM[phase * 2 + vIdx]")
# MSL promotes mixed signed/unsigned sums to uint. Support samples at the
# top/left border must remain negative for the clamp sampler, rather than wrap.
for axis, pixel in [("X", "px"), ("Y", "py")]:
    body = body.replace(f"srcBlockStart{axis} + {pixel} + config.kInputViewportOrigin{axis}",
                        f"NVF(srcBlockStart{axis}) + NVF({pixel}) + NVF(config.kInputViewportOrigin{axis})")
# All group barriers precede these checks: safely handle partial edge blocks.
body = body.replace("NVU(srcX) > config.kInputViewportWidth || NVU(dstX) > config.kOutputViewportWidth",
                    "NVU(dstX) >= config.kOutputViewportWidth")
body = body.replace("NVU(srcY) > config.kInputViewportHeight || NVU(dstY) > config.kOutputViewportHeight",
                    "NVU(dstY) >= config.kOutputViewportHeight")
tables = []
for original, name in [("coef_scale", "nisScaleCoefs"), ("coef_usm", "nisUSM")]:
    array = re.search(rf"constexpr float {original}\[kPhaseCount\]\[kFilterSize\]\s*=\s*\{{(.*?)\n\s*\}};", config, re.S)[1]
    rows = re.findall(r"\{([^}]+)\}", array)
    assert len(rows) == 64
    vectors = []
    for row in rows:
        values = [v.strip() for v in row.split(",")]
        assert len(values) == 8
        vectors += ["float4(" + ", ".join(values[i:i+4]) + ")" for i in (0, 4)]
    tables.append("constant float4 " + name + "[128] = {\n    " + ",\n    ".join(vectors) + "\n};")
aliases = """
#include <metal_stdlib>
using namespace metal;
#define NIS_SCALER 1
#define NIS_BLOCK_WIDTH 32
#define NIS_BLOCK_HEIGHT 16
#define NIS_THREAD_GROUP_SIZE 128
#define NIS_VIEWPORT_SUPPORT 1
#define NIS_TEXTURE_GATHER 0
#define NIS_NV12_SUPPORT 0
#define NIS_HDR_MODE_NONE 0
#define NIS_HDR_MODE_LINEAR 1
#define NIS_HDR_MODE_PQ 2
#define kHDRCompressionFactor 0.282842712f
#define NIS_UNROLL
#define NIS_UNROLL_INNER
#define NIS_SCALE_INT 1
#define NIS_SCALE_FLOAT 1.0f
#define NVF float
#define NVF2 float2
#define NVF3 float3
#define NVF4 float4
#define NVH float
#define NVH4 float4
#define NVI int
#define NVI2 int2
#define NVU uint
#define NVU2 uint2
#define NVB bool
#define lerp mix
#define NVTEX_SAMPLE(x, s, p) x.sample(s, p, level(0))
#define NVTEX_STORE(x, p, v) x.write(clamp(v, 0.0f, 1.0f), uint2(p))
#define NVCLAMP(x) (x)
#define GroupMemoryBarrierWithGroupSync() threadgroup_barrier(mem_flags::mem_threadgroup)
constexpr sampler samplerLinearClamp(coord::normalized, filter::linear, address::clamp_to_edge);
"""
# A 32x16 block keeps threadgroup storage within Apple's 32 KiB limit,
# including Metal shader-validation instrumentation.
shared_struct = """
struct NISShared {
    float shPixelsY[38 * 22];
    float shCoefScaler[64][6];
    float shCoefUSM[64][6];
    float4 shEdgeMap[34 * 18];
};
struct NISShader {
    constant NISConfig &config;
    threadgroup NISShared &shared;
    texture2d<float> in_texture;
    texture2d<float, access::write> out_texture;
"""
entry = """#endif
};
kernel void nisScale(texture2d<float> input [[texture(0)]],
                     texture2d<float, access::write> output [[texture(1)]],
                     constant NISConfig &config [[buffer(0)]],
                     uint2 group [[threadgroup_position_in_grid]],
                     uint lane [[thread_index_in_threadgroup]]) {
    threadgroup NISShared shared;
    NISShader shader{config, shared, input, output};
    shader.NVScaler(group, lane);
}
"""
output = license + "// Generated by BuildScripts/generate-nis-metal.py; do not edit.\n"
output += aliases + "\nstruct NISConfig {" + fields + "};\n" + "\n".join(tables)
output += "\n" + shared_struct + body + entry
(root / "NIS.metal").write_text(output)
